Spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HR_db?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: ALWAYS